# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=128)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
